-- DEPTH / SF-002 MVP v0.4
-- Run once in Supabase SQL Editor.

create table if not exists public.depth_events (
  id bigint generated by default as identity primary key,
  ts_utc timestamptz not null default now(),
  session_id text not null,
  event text not null,
  source text not null default 'direct',
  campaign text not null default 'none',
  selected text,
  mode text,
  entity text,
  depth text
);

alter table public.depth_events enable row level security;

-- MVP: anonymous visitors may INSERT analytics events only.
-- They cannot read/update/delete analytics rows.
drop policy if exists "depth_events_anon_insert" on public.depth_events;
create policy "depth_events_anon_insert"
on public.depth_events
for insert
to anon
with check (true);

grant insert on table public.depth_events to anon;
grant usage, select on sequence public.depth_events_id_seq to anon;

create index if not exists depth_events_ts_idx on public.depth_events(ts_utc desc);
create index if not exists depth_events_source_idx on public.depth_events(source, campaign);
create index if not exists depth_events_event_idx on public.depth_events(event);
